[package]
name = "rdstore"
version = "0.1.0"
authors = ["pmagaz <magazpablo@gmail.com>"]
edition = "2018"

[lib]
name = "rdstore"
path = "src/lib.rs"

[[bin]]
name = "mybin"
path = "src/main.rs"

[dependencies]
uuid = { version = "0.7.4", features = ["serde", "v4"] }
bincode = "1.2.1"
serde_json = "1.0.51"
serde_yaml = "0.8.11"
ron = "0.5.1"
failure = "0.1.7"
serde = { version = "1.0", features = ["derive"] }