[package]
name = "rust-webpush-server"
version = "0.1.0"
authors = ["pmagaz <magazpablo@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iron = "0.6.1"
mime = "0.3.13"
router = "0.6.0"
quick-error = "1.2.2"
urlencoded = "0.6.0"
futures-preview = "0.3.0-alpha.18"
dotenv = "0.14.1"
bincode = "1.1.4"
dotenv_codegen = "0.14.1"
serde = { version = "1.0", features = ["derive"] }


[dependencies.bodyparser]
git = "https://github.com/iron/body-parser.git"